# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
version: 2.1
jobs:
  checkout:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
         keys:
           - build-machine-{{ checksum "Makefile" }}
      - run:
          name: 'Prepare build environment...'
          command: |
            if [ -d "linux-stable" ]; then
              echo 'Build environment was cached.'
            else
              echo 'Build environment was not cached.'
              sudo apt-get update -qq
              sudo apt-get install -y apt-utils
              sudo apt-get install -y sudo
              sudo apt-get install -y uncrustify rsync build-essential
              sudo apt-get install -y ruby python autoconf automake libtool
              sudo apt-get install -y libncurses5-dev libncursesw5-dev bc
              sudo apt-get install -y libssl-dev pkg-config zsh libelf-dev
              sudo apt-get install -y bison flex sqlite3 libsqlite3-dev
              sudo apt-get install -y liblz4-tool liblz4-dev
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              make prepare
              make save_space
            fi
            ls
      - save_cache:
          key: build-machine-{{ checksum "Makefile" }}
          paths:
            - linux-stable
            - pristine
            - patches
      - persist_to_workspace:
          root: .
          paths:
            - linux-stable
            - pristine
            - patches
workflows:
  version: 2
  build-and-deploy:
    jobs:
        - checkout
