# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  checkout:
    docker:
      - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
         keys:
           - build-{{ checksum "Makefile" }}
      - run:
          name: 'Prepare build environment...'
          command: |
            if [ -d "~/build/linux-stable" ]; then
              echo 'Build environment was cached.'
            else
              echo 'Build environment was not cached.'
              apt-get update -qq --allow-releaseinfo-change
              apt-get install patch
              apt-get install --reinstall make
              make prepare
              make save_space
            fi
      - save_cache:
          key: build-{{ checksum "Makefile" }}
          paths:
            - build
      - persist_to_workspace:
          root: ~/build
          paths:
            - linux-stable
            - pristine
  compile:
    docker:
        - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/build
    steps:
        - checkout
        - attach_workspace:
            at: ~/build
        - run: 'apt-get update -qq --allow-releaseinfo-change'
        - run: 'apt-get install -y sudo rpm cpio'
        - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev'
        - run: 'apt-get install -y libncursesw5-dev bc pkg-config zsh libelf-dev'
        - run: 'apt-get install -y bison flex'
        - run: 'make config_circle'
        - run: 'make build'
  compile_camflow:
    docker:
        - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/build
    steps:
        - checkout
        - run: 'apt-get update -qq --allow-releaseinfo-change'
        - run: 'apt-get install -y sudo rpm cpio'
        - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev'
        - run: 'apt-get install -y libncursesw5-dev bc pkg-config zsh libelf-dev'
        - run: 'apt-get install -y bison flex'
        - run: 'git config --global user.name "Soo Yee Lim"'
        - run: 'git config --global user.email "sooyee.lim@bristol.ac.uk"'
        - run: 'make prepare_camflow'
        - run: 'make config_circle_camflow'
        - run: 'make build'
  patch:
    docker:
        - image: kernelci/build-gcc-8_x86:latest
    working_directory: ~/build
    steps:
        - checkout
        - run: 'apt-get update -qq --allow-releaseinfo-change'
        - run: 'apt-get install -y sudo rpm cpio'
        - run: 'apt-get install -y build-essential rsync libtool libncurses5-dev'
        - run: 'apt-get install -y libncursesw5-dev bc pkg-config zsh libelf-dev'
        - run: 'apt-get install -y bison flex'
        - run: 'git config --global user.name "Soo Yee Lim"'
        - run: 'git config --global user.email "sooyee.lim@bristol.ac.uk"'
        - run: 'make prepare'
        - run: 'make patch'
        - run: 'cd patches && cat 0001-provbpf.patch'
        - persist_to_workspace:
            root: ~/build
            paths:
              - patches
  fedora_x86:
    docker:
      - image: fedora:33
    resource_class: xlarge
    working_directory: ~/build
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run: 'sudo dnf install -y make wget rsync'
      - run: 'sudo dnf install -y fedpkg fedora-packager rpmdevtools ncurses-devel pesign grubby'
      - run: 'cd patches && cat 0001-provbpf.patch'
      - run:
          command: 'make fedora'
          no_output_timeout: '60m'
      - persist_to_workspace:
          root: ~/build
          paths:
            - output
workflows:
  version: 2
  build-and-deploy:
    jobs:
        - checkout
        - compile_camflow
        - compile:
            requires:
                - checkout
        - patch:
            requires:
                - checkout
        - fedora_x86:
            requires:
                - patch
                - compile
